In [1]:
import pandas as pd

In [11]:
df= pd.read_csv("/Users/nathanaelchun/Downloads/chelsea.csv")

In [12]:
df

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,702,Tammy Abraham,34,2233,15,18.082802,3,2.913048,88,21,2,0,F S,Chelsea,15,18.082802,19.841920,1.546151
1,700,Willian,36,2609,9,8.135337,7,8.679427,71,76,4,0,F M S,Chelsea,5,5.090662,18.409354,10.227612
2,2662,Christian Pulisic,25,1738,9,8.925186,4,4.296080,63,30,0,0,F M S,Chelsea,9,8.925186,16.746663,7.069777
3,502,Olivier Giroud,18,1015,8,7.400898,0,1.388367,39,8,1,0,F S,Chelsea,8,7.400898,9.754191,2.356766
4,7768,Mason Mount,37,2894,7,7.497830,5,5.258457,78,52,3,0,F M S,Chelsea,7,7.497830,16.875005,8.520663
5,1389,Jorginho,31,2391,4,3.097004,2,2.916516,12,23,10,0,M S,Chelsea,1,0.813498,15.918048,14.992467
6,1621,Marcos Alonso,18,1436,4,2.546826,2,2.991487,30,25,4,0,D M S,Chelsea,4,2.546826,10.606779,7.111681
7,751,N'Golo Kanté,22,1733,3,1.543913,0,1.520272,18,27,4,0,M S,Chelsea,3,1.543913,7.209238,4.837985
8,681,César Azpilicueta,36,3234,2,2.594344,6,6.033903,29,45,1,0,D M,Chelsea,2,2.594344,18.327021,14.643177
9,1822,Antonio Rüdiger,20,1710,2,0.930455,0,1.177513,12,5,3,0,D S,Chelsea,2,0.930455,6.220131,6.190619
10,592,Ross Barkley,21,1100,1,2.844964,4,2.860244,40,24,0,0,M S,Chelsea,1,2.844964,10.341834,6.369962
11,687,Pedro,11,661,1,2.472475,1,1.070755,22,17,1,0,F M S,Chelsea,1,2.472475,4.754026,1.556944
12,703,Fikayo Tomori,15,1299,1,0.562975,0,0.119877,7,4,3,0,D,Chelsea,1,0.562975,5.061156,4.995167
13,1678,Michy Batshuayi,16,194,1,3.038819,1,0.202504,15,3,0,0,F S,Chelsea,1,3.038819,3.128807,0.220431
14,2254,Mateo Kovacic,31,2086,1,0.972660,3,1.848453,21,28,8,0,M S,Chelsea,1,0.972660,10.112223,9.035377
15,6456,Callum Hudson-Odoi,22,816,1,2.015143,5,2.708166,21,20,1,0,F M S,Chelsea,1,2.015143,7.247336,3.847064
16,200,Andreas Christensen,21,1758,0,0.614144,0,0.851269,7,4,5,0,D,Chelsea,0,0.614144,6.598436,6.253280
17,624,Willy Caballero,5,450,0,0.000000,0,0.000000,0,0,0,0,GK,Chelsea,0,0.000000,0.146981,0.146981
18,688,Ruben Loftus-Cheek,7,195,0,0.544694,1,0.523469,4,1,0,0,F M S,Chelsea,0,0.544694,1.619940,0.551778
19,935,Kurt Zouma,28,2340,0,1.469710,0,0.121914,15,1,6,0,D S,Chelsea,0,1.469710,9.402102,9.392718
20,1245,Emerson,15,1019,0,1.099134,0,1.687929,13,19,3,0,D M S,Chelsea,0,1.099134,6.990983,5.515448
21,5061,Kepa,33,2970,0,0.000000,0,0.000000,0,0,0,0,GK,Chelsea,0,0.000000,5.265830,5.265830
22,7988,Billy Gilmour,6,190,0,0.028427,0,0.188026,1,4,0,0,M S,Chelsea,0,0.028427,1.926148,1.738122
23,8067,Reece James,24,1512,0,0.819267,2,3.181413,18,25,1,0,D M S,Chelsea,0,0.819267,7.329804,6.209258
24,8226,Tariq Lamptey,1,26,0,0.000000,0,0.069156,0,1,0,0,S,Chelsea,0,0.000000,0.069156,0.000000
25,8383,Faustino Anjorin,1,19,0,0.016683,0,0.000000,1,0,0,0,S,Chelsea,0,0.016683,0.016683,0.000000
26,8384,Armando Broja,1,4,0,0.000000,0,0.000000,0,0,0,0,S,Chelsea,0,0.000000,0.020873,0.020873

In [13]:
df.columns

Index(['id', 'player_name', 'games', 'time', 'goals', 'xG', 'assists', 'xA',
       'shots', 'key_passes', 'yellow_cards', 'red_cards', 'position',
       'team_title', 'npg', 'npxG', 'xGChain', 'xGBuildup'],
      dtype='object')

In [14]:
df.index

RangeIndex(start=0, stop=27, step=1)

In [16]:
df.player_name

0           Tammy Abraham
1                 Willian
2       Christian Pulisic
3          Olivier Giroud
4             Mason Mount
5                Jorginho
6           Marcos Alonso
7            N'Golo Kanté
8       César Azpilicueta
9         Antonio Rüdiger
10           Ross Barkley
11                  Pedro
12          Fikayo Tomori
13        Michy Batshuayi
14          Mateo Kovacic
15     Callum Hudson-Odoi
16    Andreas Christensen
17        Willy Caballero
18     Ruben Loftus-Cheek
19             Kurt Zouma
20                Emerson
21                   Kepa
22          Billy Gilmour
23            Reece James
24          Tariq Lamptey
25       Faustino Anjorin
26          Armando Broja
Name: player_name, dtype: object

In [17]:
df.goals

0     15
1      9
2      9
3      8
4      7
5      4
6      4
7      3
8      2
9      2
10     1
11     1
12     1
13     1
14     1
15     1
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
Name: goals, dtype: int64

In [18]:
df.loc[:,:]

,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,702,Tammy Abraham,34,2233,15,18.082802,3,2.913048,88,21,2,0,F S,Chelsea,15,18.082802,19.841920,1.546151
1,700,Willian,36,2609,9,8.135337,7,8.679427,71,76,4,0,F M S,Chelsea,5,5.090662,18.409354,10.227612
2,2662,Christian Pulisic,25,1738,9,8.925186,4,4.296080,63,30,0,0,F M S,Chelsea,9,8.925186,16.746663,7.069777
3,502,Olivier Giroud,18,1015,8,7.400898,0,1.388367,39,8,1,0,F S,Chelsea,8,7.400898,9.754191,2.356766
4,7768,Mason Mount,37,2894,7,7.497830,5,5.258457,78,52,3,0,F M S,Chelsea,7,7.497830,16.875005,8.520663
5,1389,Jorginho,31,2391,4,3.097004,2,2.916516,12,23,10,0,M S,Chelsea,1,0.813498,15.918048,14.992467
6,1621,Marcos Alonso,18,1436,4,2.546826,2,2.991487,30,25,4,0,D M S,Chelsea,4,2.546826,10.606779,7.111681
7,751,N'Golo Kanté,22,1733,3,1.543913,0,1.520272,18,27,4,0,M S,Chelsea,3,1.543913,7.209238,4.837985
8,681,César Azpilicueta,36,3234,2,2.594344,6,6.033903,29,45,1,0,D M,Chelsea,2,2.594344,18.327021,14.643177
9,1822,Antonio Rüdiger,20,1710,2,0.930455,0,1.177513,12,5,3,0,D S,Chelsea,2,0.930455,6.220131,6.190619
10,592,Ross Barkley,21,1100,1,2.844964,4,2.860244,40,24,0,0,M S,Chelsea,1,2.844964,10.341834,6.369962
11,687,Pedro,11,661,1,2.472475,1,1.070755,22,17,1,0,F M S,Chelsea,1,2.472475,4.754026,1.556944
12,703,Fikayo Tomori,15,1299,1,0.562975,0,0.119877,7,4,3,0,D,Chelsea,1,0.562975,5.061156,4.995167
13,1678,Michy Batshuayi,16,194,1,3.038819,1,0.202504,15,3,0,0,F S,Chelsea,1,3.038819,3.128807,0.220431
14,2254,Mateo Kovacic,31,2086,1,0.972660,3,1.848453,21,28,8,0,M S,Chelsea,1,0.972660,10.112223,9.035377
15,6456,Callum Hudson-Odoi,22,816,1,2.015143,5,2.708166,21,20,1,0,F M S,Chelsea,1,2.015143,7.247336,3.847064
16,200,Andreas Christensen,21,1758,0,0.614144,0,0.851269,7,4,5,0,D,Chelsea,0,0.614144,6.598436,6.253280
17,624,Willy Caballero,5,450,0,0.000000,0,0.000000,0,0,0,0,GK,Chelsea,0,0.000000,0.146981,0.146981
18,688,Ruben Loftus-Cheek,7,195,0,0.544694,1,0.523469,4,1,0,0,F M S,Chelsea,0,0.544694,1.619940,0.551778
19,935,Kurt Zouma,28,2340,0,1.469710,0,0.121914,15,1,6,0,D S,Chelsea,0,1.469710,9.402102,9.392718
20,1245,Emerson,15,1019,0,1.099134,0,1.687929,13,19,3,0,D M S,Chelsea,0,1.099134,6.990983,5.515448
21,5061,Kepa,33,2970,0,0.000000,0,0.000000,0,0,0,0,GK,Chelsea,0,0.000000,5.265830,5.265830
22,7988,Billy Gilmour,6,190,0,0.028427,0,0.188026,1,4,0,0,M S,Chelsea,0,0.028427,1.926148,1.738122
23,8067,Reece James,24,1512,0,0.819267,2,3.181413,18,25,1,0,D M S,Chelsea,0,0.819267,7.329804,6.209258
24,8226,Tariq Lamptey,1,26,0,0.000000,0,0.069156,0,1,0,0,S,Chelsea,0,0.000000,0.069156,0.000000
25,8383,Faustino Anjorin,1,19,0,0.016683,0,0.000000,1,0,0,0,S,Chelsea,0,0.016683,0.016683,0.000000
26,8384,Armando Broja,1,4,0,0.000000,0,0.000000,0,0,0,0,S,Chelsea,0,0.000000,0.020873,0.020873

In [21]:
df.loc[:,["player_name","assists"]]

            player_name  assists
0         Tammy Abraham        3
1               Willian        7
2     Christian Pulisic        4
3        Olivier Giroud        0
4           Mason Mount        5
5              Jorginho        2
6         Marcos Alonso        2
7          N'Golo Kanté        0
8     César Azpilicueta        6
9       Antonio Rüdiger        0
10         Ross Barkley        4
11                Pedro        1
12        Fikayo Tomori        0
13      Michy Batshuayi        1
14        Mateo Kovacic        3
15   Callum Hudson-Odoi        5
16  Andreas Christensen        0
17      Willy Caballero        0
18   Ruben Loftus-Cheek        1
19           Kurt Zouma        0
20              Emerson        0
21                 Kepa        0
22        Billy Gilmour        0
23          Reece James        2
24        Tariq Lamptey        0
25     Faustino Anjorin        0
26        Armando Broja        0

In [23]:
df.loc[:,["player_name","assists"]].sort_values("assists")

            player_name  assists
26        Armando Broja        0
24        Tariq Lamptey        0
22        Billy Gilmour        0
3        Olivier Giroud        0
21                 Kepa        0
20              Emerson        0
19           Kurt Zouma        0
7          N'Golo Kanté        0
9       Antonio Rüdiger        0
17      Willy Caballero        0
16  Andreas Christensen        0
12        Fikayo Tomori        0
25     Faustino Anjorin        0
18   Ruben Loftus-Cheek        1
13      Michy Batshuayi        1
11                Pedro        1
6         Marcos Alonso        2
5              Jorginho        2
23          Reece James        2
14        Mateo Kovacic        3
0         Tammy Abraham        3
10         Ross Barkley        4
2     Christian Pulisic        4
15   Callum Hudson-Odoi        5
4           Mason Mount        5
8     César Azpilicueta        6
1               Willian        7

In [24]:
df2 = df.loc[:,["player_name","assists"]]

In [25]:
df2.sort_values("assists",ascending=False)

            player_name  assists
1               Willian        7
8     César Azpilicueta        6
4           Mason Mount        5
15   Callum Hudson-Odoi        5
2     Christian Pulisic        4
10         Ross Barkley        4
0         Tammy Abraham        3
14        Mateo Kovacic        3
23          Reece James        2
5              Jorginho        2
6         Marcos Alonso        2
18   Ruben Loftus-Cheek        1
13      Michy Batshuayi        1
11                Pedro        1
12        Fikayo Tomori        0
9       Antonio Rüdiger        0
16  Andreas Christensen        0
17      Willy Caballero        0
7          N'Golo Kanté        0
19           Kurt Zouma        0
20              Emerson        0
21                 Kepa        0
22        Billy Gilmour        0
3        Olivier Giroud        0
24        Tariq Lamptey        0
25     Faustino Anjorin        0
26        Armando Broja        0